apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  - generictopologyprocessor-deployment.yaml
  - generictopologyprocessor-service.yaml
  - generictopologyprocessor-serviceaccount.yaml
  - generictopologyprocessor-observerrole.yaml
  - generictopologyprocessor-observerrolebinding.yaml
  - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: java-grpc-connector-template
    newName: docker.io/sghung/sample-java-template
    newTag: latest
  - name: generic-topology-processor
    newName: cp.icr.io/cp/cp4waiops/generic-topology-processor
    newTag: v4.1.1-20230716.2205-62247c872